<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy import stats

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [2]:
samples_1 = np.arange(-15, 27, 0.7)
samples_1

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [4]:
samples_2 = np.random.normal(2.7, 1.2, 40)
samples_2

array([ 4.08332155,  3.12006974,  1.60368079,  3.69965442,  4.73259331,
        2.03084111,  3.80244725,  2.58180036,  2.38467633,  0.67430126,
        2.87441167,  5.24737575,  0.56925143,  3.31047033, -0.07178426,
        3.70014073,  2.67335965,  2.95205502,  3.92729667,  2.96496179,
        3.02924234,  2.00670405,  3.17924472,  2.33497478,  3.8212941 ,
        1.98530494,  3.02827357,  1.11148009,  4.25147762,  0.7603577 ,
        2.52921137,  1.39720857,  1.45752727,  2.39456741,  2.16408567,
        2.43282676,  1.87606662,  3.26520266,  3.01989345,  1.10470745])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [6]:
samples_3 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)
samples_3

array(['Britain', 'Singapore', 'Viet Nam', 'France', 'Viet Nam',
       'Viet Nam', 'Russia', 'Britain', 'Britain', 'Singapore', 'Russia',
       'France', 'Viet Nam', 'Singapore', 'Russia', 'Viet Nam', 'Russia'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [10]:
#Sinh ngẫu nhiên chuỗi các thành phố ở trên nhưng không theo phân phối chuẩn mà theo đặc tả xác suất sau [0.2, 0.1, 0.2, 0.3, 0.2]
#Lưu ý: tổng các xác suất của p bằng 1
samples_4 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 10, p = [0.2, 0.1, 0.2, 0.3, 0.2])
print(samples_4)

['Viet Nam' 'Russia' 'Russia' 'Singapore' 'Russia' 'Russia' 'Viet Nam'
 'France' 'Viet Nam' 'France']


Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [11]:
samples_5 = stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)
print(samples_5[:10])

[10.6498093   8.36802291 10.60269216 11.70454889 18.29312222 12.5115547
 11.80731195 12.31732249 10.26265114 13.02712379]


2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [17]:
samples_6 = stats.poisson.rvs(loc=56, mu = 34, size = 200)
print(samples_6[:10])

[ 88  80  94 101  81  87  88  87 106  93]
