<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/B%C3%A0i_t%E1%BA%ADp_numpy_s%E1%BB%91_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [23]:
import numpy as np

Tạo một vector a có 7 chiều với hàm np.arange()

In [125]:
a = np.arange(7).reshape(1,7)
aa = a.T
print("vector a: ", a)
print("Chuyển vị của vector a: \n", aa)
print("số chiều của vector a: ", a.ndim)
print("số chiều vector chuyển vị của vector a: ", aa.ndim)
print("kích thước của vector a: ", a.shape)
print("kích thước vector chuyển vị của vector a: ", aa.shape)

vector a:  [[0 1 2 3 4 5 6]]
Chuyển vị của vector a: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
số chiều của vector a:  2
số chiều vector chuyển vị của vector a:  2
kích thước của vector a:  (1, 7)
kích thước vector chuyển vị của vector a:  (7, 1)


Tạo một vector a có 7 chiều với hàm linspace()

In [124]:
b = np.linspace(1, 10, 7, dtype=int).reshape(1,7)
bb = b.T
print("vector a: ", b)
print("Chuyển vị của vector a: \n", bb)
print("số chiều của vector a: ", b.ndim)
print("số chiều vector chuyển vị của vector a: ", bb.ndim)
print("kích thước của vector a: ", b.shape)
print("kích thước vector chuyển vị của vector a: ", bb.shape)

vector a:  [[ 1  2  4  5  7  8 10]]
Chuyển vị của vector a: 
 [[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [10]]
số chiều của vector a:  2
số chiều vector chuyển vị của vector a:  2
kích thước của vector a:  (1, 7)
kích thước vector chuyển vị của vector a:  (7, 1)


Tạo một vector a có 7 chiều với hàm np.logspace()

In [126]:
c = np.logspace(1, 2, 7, dtype=int).reshape(1,7)
cc = c.T

print("vector a: ", c)
print("Chuyển vị của vector a: \n", cc)
print("số chiều của vector a: ", c.ndim)
print("số chiều vector chuyển vị của vector a: ", cc.ndim)
print("kích thước của vector a: ", c.shape)
print("kích thước vector chuyển vị của vector a: ", cc.shape)

vector a:  [[ 10  14  21  31  46  68 100]]
Chuyển vị của vector a: 
 [[ 10]
 [ 14]
 [ 21]
 [ 31]
 [ 46]
 [ 68]
 [100]]
số chiều của vector a:  2
số chiều vector chuyển vị của vector a:  2
kích thước của vector a:  (1, 7)
kích thước vector chuyển vị của vector a:  (7, 1)


Tạo một vector a có 7 chiều với hàm np.random.randint()

In [132]:
d = np.random.rand(1,7)
dd = d.T
print("vector a: ", d)
print("Chuyển vị của vector a: \n", dd)
print("số chiều của vector a: ", d.ndim)
print("số chiều vector chuyển vị của vector a: ", dd.ndim)
print("kích thước của vector a: ", d.shape)
print("kích thước vector chuyển vị của vector a: ", dd.shape)

vector a:  [[0.38898467 0.72929703 0.14460932 0.94821207 0.20565064 0.22562406
  0.77791014]]
Chuyển vị của vector a: 
 [[0.38898467]
 [0.72929703]
 [0.14460932]
 [0.94821207]
 [0.20565064]
 [0.22562406]
 [0.77791014]]
số chiều của vector a:  2
số chiều vector chuyển vị của vector a:  2
kích thước của vector a:  (1, 7)
kích thước vector chuyển vị của vector a:  (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A được sinh bởi:
- np.arange()
- np.linspace()
- np.logspace()
- np.random.rand()

Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận A và ma trận $A^T$

ma trận A10x7 với giá trị các phần tử của ma trận A được sinh bởi hàm np.arange()

In [66]:
e = np.arange(70).reshape(7,10)
ee = e.T
print("ma trận A: \n", e)
print("Chuyển vị của ma trận A: \n", ee)
print("số chiều của ma trận A: ", e.ndim)
print("số chiều vector chuyển vị của ma trận A:: ", ee.ndim)
print("kích thước của ma trận A:: ", e.shape)
print("kích thước vector chuyển vị của ma trận A: ", ee.shape)

ma trận A: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
Chuyển vị của ma trận A: 
 [[ 0 10 20 30 40 50 60]
 [ 1 11 21 31 41 51 61]
 [ 2 12 22 32 42 52 62]
 [ 3 13 23 33 43 53 63]
 [ 4 14 24 34 44 54 64]
 [ 5 15 25 35 45 55 65]
 [ 6 16 26 36 46 56 66]
 [ 7 17 27 37 47 57 67]
 [ 8 18 28 38 48 58 68]
 [ 9 19 29 39 49 59 69]]
số chiều của ma trận A:  2
số chiều vector chuyển vị của ma trận A::  2
kích thước của ma trận A::  (7, 10)
kích thước vector chuyển vị của ma trận A:  (10, 7)


ma trận A10x7 với giá trị các phần tử của ma trận A được sinh bởi hàm linspace()

In [104]:
f = np.linspace(1, 10, 70, dtype=int).reshape(7,10)
ff = f.T
print("ma trận A: \n", f)
print("Chuyển vị của ma trận A: \n", ff)
print("số chiều của ma trận A: ", f.ndim)
print("số chiều vector chuyển vị của ma trận A:: ", ff.ndim)
print("kích thước của ma trận A:: ", f.shape)
print("kích thước vector chuyển vị của ma trận A: ", ff.shape)

ma trận A: 
 [[ 1  1  1  1  1  1  1  1  2  2]
 [ 2  2  2  2  2  2  3  3  3  3]
 [ 3  3  3  4  4  4  4  4  4  4]
 [ 4  5  5  5  5  5  5  5  5  6]
 [ 6  6  6  6  6  6  7  7  7  7]
 [ 7  7  7  7  8  8  8  8  8  8]
 [ 8  8  9  9  9  9  9  9  9 10]]
Chuyển vị của ma trận A: 
 [[ 1  2  3  4  6  7  8]
 [ 1  2  3  5  6  7  8]
 [ 1  2  3  5  6  7  9]
 [ 1  2  4  5  6  7  9]
 [ 1  2  4  5  6  8  9]
 [ 1  2  4  5  6  8  9]
 [ 1  3  4  5  7  8  9]
 [ 1  3  4  5  7  8  9]
 [ 2  3  4  5  7  8  9]
 [ 2  3  4  6  7  8 10]]
số chiều của ma trận A:  2
số chiều vector chuyển vị của ma trận A::  2
kích thước của ma trận A::  (7, 10)
kích thước vector chuyển vị của ma trận A:  (10, 7)


ma trận A10x7 với giá trị các phần tử của ma trận A được sinh bởi hàm logspace()

In [109]:
g = np.logspace(2, 4, 70, dtype=int).reshape(7,10)
gg = g.T
print("ma trận A: \n", g)
print("Chuyển vị của ma trận A: \n", gg)
print("số chiều của ma trận A: ", g.ndim)
print("số chiều vector chuyển vị của ma trận A:: ", gg.ndim)
print("kích thước của ma trận A:: ", g.shape)
print("kích thước vector chuyển vị của ma trận A: ", gg.shape)

ma trận A: 
 [[  100   106   114   122   130   139   149   159   170   182]
 [  194   208   222   238   254   272   290   310   332   355]
 [  379   406   434   464   496   530   567   606   648   692]
 [  740   791   846   904   967  1033  1105  1181  1263  1350]
 [ 1443  1543  1649  1763  1885  2015  2154  2303  2462  2632]
 [ 2813  3007  3215  3437  3674  3928  4199  4489  4799  5130]
 [ 5484  5862  6267  6700  7162  7656  8185  8750  9354 10000]]
Chuyển vị của ma trận A: 
 [[  100   194   379   740  1443  2813  5484]
 [  106   208   406   791  1543  3007  5862]
 [  114   222   434   846  1649  3215  6267]
 [  122   238   464   904  1763  3437  6700]
 [  130   254   496   967  1885  3674  7162]
 [  139   272   530  1033  2015  3928  7656]
 [  149   290   567  1105  2154  4199  8185]
 [  159   310   606  1181  2303  4489  8750]
 [  170   332   648  1263  2462  4799  9354]
 [  182   355   692  1350  2632  5130 10000]]
số chiều của ma trận A:  2
số chiều vector chuyển vị của ma trận A:

ma trận A10x7 với giá trị các phần tử của ma trận A được sinh bởi hàm rand.rand()

In [121]:
h = np.random.rand(7,10)
hh = h.T
print("ma trận A: \n", h)
print("Chuyển vị của ma trận A: \n", hh)
print("số chiều của ma trận A: ", h.ndim)
print("số chiều vector chuyển vị của ma trận A:: ", hh.ndim)
print("kích thước của ma trận A:: ", h.shape)
print("kích thước vector chuyển vị của ma trận A: ", hh.shape)

ma trận A: 
 [[0.95271769 0.88354293 0.54360155 0.40016333 0.17349606 0.61136277
  0.52490016 0.54028169 0.32526351 0.82890942]
 [0.75214941 0.34666893 0.24807049 0.75523948 0.06428944 0.33490539
  0.64674642 0.15848426 0.07154189 0.68400728]
 [0.73310112 0.29143707 0.4723331  0.64778756 0.54144082 0.3575878
  0.98321038 0.24449929 0.39285297 0.83627056]
 [0.29196456 0.33684567 0.9041108  0.19807452 0.12030331 0.33988389
  0.76328491 0.44783896 0.38153829 0.19698638]
 [0.22382175 0.59148588 0.65042453 0.87678148 0.88217876 0.00847352
  0.16659811 0.4573051  0.00342991 0.47887448]
 [0.745354   0.15971692 0.31933874 0.77088202 0.97010242 0.12951073
  0.6082343  0.8937625  0.19353356 0.637885  ]
 [0.08862673 0.96223121 0.59745215 0.68673839 0.38003113 0.57083395
  0.86413473 0.56841911 0.86493812 0.36732087]]
Chuyển vị của ma trận A: 
 [[0.95271769 0.75214941 0.73310112 0.29196456 0.22382175 0.745354
  0.08862673]
 [0.88354293 0.34666893 0.29143707 0.33684567 0.59148588 0.15971692
  0.962

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

ma trận của hàm np.arange()

In [105]:
print("ma trận A: \n", e)
print("Chuyển ma trận A thành vector: \n", e.flatten())
print("chuyển vector thành ma trận: \n", e.reshape(10,7))

ma trận A: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
Chuyển ma trận A thành vector: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
chuyển vector thành ma trận: 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]


ma trận của hàm np.linspace()

In [106]:
print("ma trận A: \n", f)
print("Chuyển ma trận A thành vector: \n", f.flatten())
print("chuyển vector thành ma trận: \n", f.reshape(10,7))

ma trận A: 
 [[ 1  1  1  1  1  1  1  1  2  2]
 [ 2  2  2  2  2  2  3  3  3  3]
 [ 3  3  3  4  4  4  4  4  4  4]
 [ 4  5  5  5  5  5  5  5  5  6]
 [ 6  6  6  6  6  6  7  7  7  7]
 [ 7  7  7  7  8  8  8  8  8  8]
 [ 8  8  9  9  9  9  9  9  9 10]]
Chuyển ma trận A thành vector: 
 [ 1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  4
  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  7  7
  7  7  7  7  7  7  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9 10]
chuyển vector thành ma trận: 
 [[ 1  1  1  1  1  1  1]
 [ 1  2  2  2  2  2  2]
 [ 2  2  3  3  3  3  3]
 [ 3  3  4  4  4  4  4]
 [ 4  4  4  5  5  5  5]
 [ 5  5  5  5  6  6  6]
 [ 6  6  6  6  7  7  7]
 [ 7  7  7  7  7  8  8]
 [ 8  8  8  8  8  8  9]
 [ 9  9  9  9  9  9 10]]


ma trận của hàm np.logspace()

In [107]:
print("ma trận A: \n", g)
print("Chuyển ma trận A thành vector: \n", g.flatten())
print("chuyển vector thành ma trận: \n", g.reshape(10,7))

ma trận A: 
 [[   10    11    12    13    14    16    18    20    22    24]
 [   27    30    33    36    40    44    49    54    60    67]
 [   74    81    90   100   110   122   135   149   164   182]
 [  201   222   246   272   300   332   367   406   448   496]
 [  548   606   670   740   818   904  1000  1105  1221  1350]
 [ 1492  1649  1823  2015  2227  2462  2721  3007  3324  3674]
 [ 4061  4489  4961  5484  6061  6700  7405  8185  9047 10000]]
Chuyển ma trận A thành vector: 
 [   10    11    12    13    14    16    18    20    22    24    27    30
    33    36    40    44    49    54    60    67    74    81    90   100
   110   122   135   149   164   182   201   222   246   272   300   332
   367   406   448   496   548   606   670   740   818   904  1000  1105
  1221  1350  1492  1649  1823  2015  2227  2462  2721  3007  3324  3674
  4061  4489  4961  5484  6061  6700  7405  8185  9047 10000]
chuyển vector thành ma trận: 
 [[   10    11    12    13    14    16    18]
 [   20  

ma trận của hàm np.random.rand()

In [108]:
print("ma trận A: \n", h)
print("Chuyển ma trận A thành vector: \n", h.flatten())
print("chuyển vector thành ma trận: \n", h.reshape(10,7))

ma trận A: 
 [[0.28585355 0.27120257 0.79908141 0.35562405 0.63760028 0.75588536
  0.01618849 0.45430366 0.5155601  0.41674244]
 [0.28784763 0.99904563 0.84530861 0.22398521 0.26847938 0.64543252
  0.5147452  0.96413384 0.68504565 0.32056024]
 [0.08077124 0.43661457 0.42124043 0.83551662 0.68620791 0.88555397
  0.14470727 0.04319661 0.71367718 0.20965375]
 [0.18113188 0.85166589 0.14753824 0.89923251 0.34470083 0.08803584
  0.95610674 0.90725947 0.03503272 0.15533342]
 [0.64597628 0.23712078 0.73659445 0.42796477 0.68688709 0.4910363
  0.11761898 0.99096512 0.31476245 0.8248755 ]
 [0.87368136 0.90575667 0.78846523 0.1344777  0.16505492 0.15989429
  0.11894046 0.29824068 0.63336436 0.05163994]
 [0.17361525 0.33523181 0.6747266  0.5941698  0.76778827 0.16596999
  0.83943188 0.34736175 0.5204347  0.66544753]]
Chuyển ma trận A thành vector: 
 [0.28585355 0.27120257 0.79908141 0.35562405 0.63760028 0.75588536
 0.01618849 0.45430366 0.5155601  0.41674244 0.28784763 0.99904563
 0.84530861 0.2

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [8]:
ma_tran = np.logspace(1, 3, num=150, dtype=int).reshape(10,15)
print(ma_tran)
print("dòng thứ 3 của ma trận A: \n",ma_tran[2])
print("cột thứ 5 của ma trận A: \n", ma_tran[:,4])

[[  10   10   10   10   11   11   12   12   12   13   13   14   14   14
    15]
 [  15   16   16   17   17   18   19   19   20   20   21   22   23   23
    24]
 [  25   26   26   27   28   29   30   31   32   33   34   35   36   37
    38]
 [  40   41   42   44   45   46   48   49   51   53   54   56   58   60
    61]
 [  63   65   67   70   72   74   76   79   81   84   87   89   92   95
    98]
 [ 101  104  108  111  114  118  122  126  130  134  138  142  147  151
   156]
 [ 161  166  171  177  182  188  194  200  206  213  219  226  233  241
   248]
 [ 256  264  273  281  290  299  308  318  328  339  349  360  371  383
   395]
 [ 408  420  434  447  461  476  491  506  522  538  555  573  591  609
   629]
 [ 648  669  690  711  734  757  780  805  830  856  883  911  940  969
  1000]]
dòng thứ 3 của ma trận A: 
 [25 26 26 27 28 29 30 31 32 33 34 35 36 37 38]
cột thứ 5 của ma trận A: 
 [ 11  17  28  45  72 114 182 290 461 734]


Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [9]:
import numpy as np 
import statistics as sta

Xây dựng hàm tính giá trị trung bình

In [22]:
def gia_tri_trung_binh(ma_tran_A):
  tb = np.mean(ma_tran_A)
  return tb

Xây dựng hàm tính giá trị trung vị

In [28]:
def gia_tri_trung_vi(ma_tran_A):
  tv = np.median(ma_tran_A)
  return tv

Xây dựng hàm tính giá trị yếu vị

In [29]:
def gia_tri_yeu_vi(ma_tran_A):
  return

Xây dựng hàm tính phương sai

In [30]:
def phuong_sai(ma_tran_A):
  ps = sta.variance(ma_tran_A)
  return ps

Xây dựng hàm tính độ lệch chuẩn

In [31]:
def do_lech_chuan(ma_tran_A):
  dlc = sta.stdev(ma_tran_A)
  return dlc

In [32]:
import numpy as np
ma_tran_A = np.arange(150).reshape(15,10)
ma_tran_A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]])

Áp dụng 5 hàm ở trên cho từng hàng của ma trận A

In [27]:
print("Giá trị trung bình cho từng hàng của ma trận A là: \n", np.apply_along_axis(gia_tri_trung_binh, 1, ma_tran_A))

Giá trị trung bình cho từng hàng của ma trận A là: 
 [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]


In [33]:
print("Giá trị trung vị cho từng hàng của ma trận A là: \n", np.apply_along_axis(gia_tri_trung_vi, 1, ma_tran_A))

Giá trị trung vị cho từng hàng của ma trận A là: 
 [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]


In [34]:
print("Phương sai cho từng hàng của ma trận A là: \n", np.apply_along_axis(phuong_sai, 1, ma_tran_A))

Phương sai cho từng hàng của ma trận A là: 
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [35]:
print("Độ lệch chuẩn cho từng hàng của ma trận A là: \n", np.apply_along_axis(do_lech_chuan, 1, ma_tran_A))

Độ lệch chuẩn cho từng hàng của ma trận A là: 
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [36]:
print("Giá trị trung bình cho từng cột của ma trận A là: \n", np.apply_along_axis(gia_tri_trung_binh, 0, ma_tran_A))

Giá trị trung bình cho từng cột của ma trận A là: 
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]


In [37]:
print("Giá trị trung vị cho từng cột của ma trận A là: \n", np.apply_along_axis(gia_tri_trung_vi, 0, ma_tran_A))

Giá trị trung vị cho từng cột của ma trận A là: 
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]


In [38]:
print("Phương sai cho từng cột của ma trận A là: \n", np.apply_along_axis(phuong_sai, 0, ma_tran_A))

Phương sai cho từng cột của ma trận A là: 
 [2000 2000 2000 2000 2000 2000 2000 2000 2000 2000]


In [41]:
print("Độ lệch chuẩn cho từng cột của ma trận A là: \n", np.apply_along_axis(do_lech_chuan, 0, ma_tran_A))

Độ lệch chuẩn cho từng cột của ma trận A là: 
 [44.72135955 44.72135955 44.72135955 44.72135955 44.72135955 44.72135955
 44.72135955 44.72135955 44.72135955 44.72135955]
