<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/b%C3%A0i_t%E1%BA%ADp_numpy_s%E1%BB%91_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

CÚ PHÁP: np.apply_along_axis(func1d, axis, arr, args, kwargs)

- func1d(hàm): hàm này chấp nhận mảng 1 chiều,nó được áp dụng cho các mảng 1 chiều của ma trận theo trục được chỉ định

- axis(số nguyên): trục dọc của ma trận được cắt

- arr(ma trận): ma trận được nhập vào

- args: đối số bổ sung cho func1d

- kwargs: đối số được đặt tên bổ sung cho func1d

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [2]:
import numpy as np

A = np.random.randint(low=-20, high=20, size=(15,17))
print("ma trận A15x17: \n", A)

ma trận A15x17: 
 [[-19  16  -4 -10  12   2  14  11  10  -8  12  18  18   4  -8   6   9]
 [-20   3   5  13  15  15  14   4   5   0 -12   8 -16 -12  -1  -7  -9]
 [ 18  17  -4   2  -2  -7   6 -15  -8  -5  -7  -4 -19  -5  -5   9  -5]
 [ -2  10 -19  14   7   7 -16  -6   3 -10   4   0 -10  16   5 -19  -4]
 [ 18  15  -3  -4  -6   0 -15 -13   6 -17 -20   8   4 -10 -12   4 -19]
 [ 16   7   2  -6 -18 -13  14   3  18 -14  12  -2 -17 -10 -15  11 -11]
 [-11 -18   0  12   3  10   8   5  -5 -16 -12   4   2  17  -2  10  10]
 [  1  11  -2  -6  16  -4  14  18   9   0   5 -19  -5 -14  -2 -11 -16]
 [ -8  16 -19   3  -3   9   3  18 -14  17 -19 -20  10  -5   3 -15   0]
 [  7  16   6  14  12   6  -7   3  -5  -8  14 -11  -7 -12   5  13  19]
 [ 11  -6  17   3  -6  11 -18 -19  -1 -16  -2 -16  -7   7   7  13   3]
 [  4  10  -3  -6 -16   6 -10 -19  18  -6 -14  15   8   7  -6  -2 -19]
 [-15   2   4   3 -12 -20  19 -15  19  -8 -19 -14  17  -9  -4  13  16]
 [ -7  -7  11  -4   1  10  16   2  -6  -2 -17   1  11  16  

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [3]:
def tim_gia_tri_lon_nhat(vector_a):
  max = np.max(vector_a)
  return max
# 0,-2 cột
# 1,-1 hàng
z = np.apply_along_axis(tim_gia_tri_lon_nhat, 1, A)
print(z)

[18 15 18 16 18 18 17 18 18 19 17 18 19 16 17]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def tim_gia_tri_nho_nhat(vector_a):
  min = np.min(vector_a)
  return min

q = np.apply_along_axis(tim_gia_tri_nho_nhat, 0, A)
print(q)

[-20 -18 -19 -10 -18 -20 -18 -19 -14 -17 -20 -20 -19 -14 -15 -19 -19]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [5]:
def tinh_tong(vector_a):
  tong = np.sum(vector_a)
  return tong
# 0,-2 cột
# 1,-1 hàng
w = np.apply_along_axis(tinh_tong, 1, A)
print(w)

[ 83   5 -34 -20 -64 -23  17  -5 -24  65 -19 -33 -23  24  36]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [10]:
def tinh_tong_2(vector_a):
  return np.sum(vector_a[vector_a%2!=0])
# từng cột
print(np.apply_along_axis(tinh_tong_2, 0, A))
# từng hàng
np.apply_along_axis(tinh_tong_2, 1, A)

[-33  63  -4  22  23  22   0 -59  25  -5 -57  -9 -27  12  -2  -7 -33]


array([  1,  39, -42, -16, -52, -35,   9,  -9, -26,  17,  45, -19,  13,
       -24,  30])