<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/b%C3%A0i_t%E1%BA%ADp_numpy_s%E1%BB%91_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
import numpy as np

A =np.random.randint(low=-10, high=10, size=(7,5))
print(A)

[[-10  -2  -4   0   7]
 [  0   1   3  -5  -4]
 [  6   5  -2   1  -1]
 [ -3  -8   9  -1  -3]
 [-10   9  -9   6  -7]
 [ -6  -9   2   8  -7]
 [ -5   0  -1  -5   7]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [ ]:
import numpy as np

A = np.zeros((6,7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×7, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
import numpy as np

A = np.random.randint(low=-10, high=10, size=(7,7))
print(A)

[[-10  -7  -9   0  -4  -3  -8]
 [ -7  -5  -8  -6  -2   0  -9]
 [ -2   5  -7 -10  -2   2  -8]
 [ -9  -9  -6   9  -3  -5  -4]
 [  2  -5  -4   0   4   5  -5]
 [  8   3  -8  -4  -6   9   7]
 [  0   1  -6  -1   6  -6  -6]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0 trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [ ]:
import numpy as np

A = np.zeros((6,6))
np.fill_diagonal(A,15)
print(A)

[[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm numpy.triu(). Kết quả xuất ra màn hình.

In [ ]:
import numpy as np

A = np.random.randint(low=-10, high=10, size=(8,8))
AA = np.triu(A,1)
print(AA)

[[ 0  3 -3 -5  8  7 -6  3]
 [ 0  0 -4 -7  3  7 -2  0]
 [ 0  0  0  2  3 -6  6  6]
 [ 0  0  0  0 -6 -8 -5 -2]
 [ 0  0  0  0  0  3 -6 -7]
 [ 0  0  0  0  0  0 -6 -2]
 [ 0  0  0  0  0  0  0 -9]
 [ 0  0  0  0  0  0  0  0]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [ ]:
import numpy as np

A = np.random.randint(low=-10, high=10, size=(8,8))
AA = np.tril(A,-1)
print(AA)

[[  0   0   0   0   0   0   0   0]
 [ -4   0   0   0   0   0   0   0]
 [ -7   8   0   0   0   0   0   0]
 [  6   5   5   0   0   0   0   0]
 [ -7  -8  -9   3   0   0   0   0]
 [  5  -6  -2  -2   8   0   0   0]
 [  3  -1  -7   5   8   3   0   0]
 [  2  -7   7   0  -7  -9 -10   0]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [ ]:
import numpy as np

I = np.identity(9)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:

In [ ]:
import numpy as np

#Sinh ngẫu nhiên 2 ma trận có kích thước 6x7. 
#Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.

max1 = np.random.randint(low=-10, high=10, size=(6,7))
print("ma trận A: \n", max1)
max2 = np.random.randint(low=-10, high=10, size=(6,7))
print("ma trận B: \n", max2)

print("ma trận C: \n", max1 + max2)

ma trận A: 
 [[ -8  -8   1   6  -9  -9   0]
 [  3   0  -2  -5   9   3   1]
 [ -7  -8  -1  -4   2   0   1]
 [ -1  -4 -10  -9  -9   5   1]
 [  1   5 -10   0  -5   6 -10]
 [  6  -1  -3   5   4  -9   2]]
ma trận B: 
 [[  9   4  -5 -10  -2   7  -9]
 [  9  -5   4  -9  -4   7   2]
 [ -6   8  -7   0   0   0   1]
 [  2  -3   2  -1   7 -10   0]
 [  8   4   4   7  -1   0  -2]
 [  8 -10  -8  -5   3  -2  -1]]
ma trận C: 
 [[  1  -4  -4  -4 -11  -2  -9]
 [ 12  -5   2 -14   5  10   3]
 [-13   0  -8  -4   2   0   2]
 [  1  -7  -8 -10  -2  -5   1]
 [  9   9  -6   7  -6   6 -12]
 [ 14 -11 -11   0   7 -11   1]]


In [ ]:
# sinh ngẫu nhiên 1 ma trận có kích thước 5x8. 
# Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này.
# Kết quả xuất ra màn hình.
import numpy as np

max3 = np.random.randint(low=-10, high=10, size=(5,8))
m = int(input("nhập 1 số: "))
print("phép nhân vô hướng", m, "với ma trận: \n", m*max3)

nhập 1 số: 2
phép nhân vô hướng 2 với ma trận: 
 [[-10  14  12 -16  -6   0 -16  -6]
 [-10  12  18 -10 -18  12 -12 -12]
 [ -4   8  16 -18  18   2 -18 -14]
 [-16 -20  12  10 -10  -8  14 -10]
 [ 16  -2  -6   8 -20   2   2  -6]]


In [ ]:
# Sinh ngẫu nhiên một ma trận có kích thước 3x7. 
# Thực hiện phép chuyển vị đối với ma trận này. 
# Xuất các ma trận này ra màn hình.
import numpy as np

max4 = np.random.randint(low=-10, high=10, size=(3,7))
print("ma trận: \n", max4)
print("Phép chuyển vị ma trận: \n", max4.T)

ma trận: 
 [[ -6   4   5   6  -7  -7   7]
 [  8  -6  -5   3   6  -8   2]
 [  2 -10   3  -9  -8  -7  -3]]
Phép chuyển vị ma trận: 
 [[ -6   8   2]
 [  4  -6 -10]
 [  5  -5   3]
 [  6   3  -9]
 [ -7   6  -8]
 [ -7  -8  -7]
 [  7   2  -3]]


In [ ]:
# Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
# tiến hành nhân 2 ma trận này để thu được ma trận C5×3. 
# Xuất các ma trận trên ra màn hình. Gợi ý: sử dụng hàm numpy.dot()
import numpy as np

max5 = np.random.randint(low=-10, high=10, size=(5,7))
print("ma trận A5x7: \n", max5)
max6 = np.random.randint(low=-10, high=10, size=(7,3))
print("ma trận B7x3: \n", max6)

print("ma trận C5x3: \n" , np.dot(max5,max6))

ma trận A5x7: 
 [[ -5  -3   9 -10  -4   5  -8]
 [-10   1   9  -1   4   5   2]
 [  2  -7  -7  -5   7   9   2]
 [  7  -8   5   8   5  -7  -9]
 [ -8   0  -3   0  -9   0   1]]
ma trận B7x3: 
 [[ -1   2   4]
 [  7  -5   1]
 [  9  -9   1]
 [ -7   4  -7]
 [-10  -1  -6]
 [ -7  -8  -1]
 [  7   1  -5]]
ma trận C5x3: 
 [[  84 -160  115]
 [  44 -152  -62]
 [-198    5  -32]
 [-138   83   -9]
 [  78   21   14]]


In [1]:
# Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. 
# Gợi ý: sử dụng hàm numpy.linalg.inv()
import numpy as np

max7 = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
print("ma trận A5x7: \n", max7)
print("ma trận khả nghịch của A là: \n", np.linalg.inv(max7))

ma trận A5x7: 
 [[1 2 3]
 [2 5 3]
 [1 0 8]]
ma trận khả nghịch của A là: 
 [[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau

In [ ]:
# Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. 
# Hãy tạo ngẫu nhiên 1 vector hàng x có kích thước 1 × 8. 
# Kết quả xuất ra màn hình.
import numpy as np

row_vector = np.random.randint(low=-10, high=10, size=(1,8))
print(row_vector)

[[ -5   3  -1  -6  -3 -10   5   8]]


In [ ]:
# Vector cột (column vector) thực chất là ma trận có kích thước m × 1. 
# Hãy tạo ngẫu nhiên 1 vector cột x có kích thước 8 × 1. 
# Kết quả xuất ra màn hình.
import numpy as np

column_vector = np.random.randint(low=-10, high=10, size=(8,1))
print(column_vector)

[[ 3]
 [ 9]
 [-8]
 [ 3]
 [-8]
 [-3]
 [ 8]
 [-6]]


Bài 10 - Hệ phương trình tuyến tính: