<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/b%C3%A0i_t%E1%BA%ADp_numpy_s%E1%BB%91_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SƠ LƯỢC NUMPY:
- **Numpy** là một thư viện lõi phục vụ cho khoa học máy tính của Python, hỗ trợ cho việc tính toán các mảng nhiều chiều, có kích thước lớn với các hàm đã được tối ưu áp dụng lên các mảng nhiều chiều đó. Numpy đặc biệt hữu ích khi thực hiện các hàm liên quan tới Đại Số Tuyến Tính.
- Khai báo numpy: ***import numpy as np***

Bài 1: Xét không gian $R^3$, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [1]:
import numpy as np
A = np.array([5,7,14]) #khởi tạo mảng 1 chiều
print(A)

[ 5  7 14]


Bài 2: Mở rộng không gian lên $R^15$, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [2]:
import numpy as np
A = np.array([i+1 for i in range(15)]) #khởi tạo mảng 1 chiều
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian $R^n$ với n là số nguyên dương được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [7]:
import numpy as np

n = int(input("Nhập n: "))
A = np.random.randint(-10, 10, n)
print(A)

Nhập n: 5
[-7 -1 -5  4 -6]


Bài 4: Hãy viết chương trình tính chiều dài của vector OA=[7,-5,8]

In [8]:
import numpy as np

OA = np.array([7,-5,8])
print(OA)
chieu_dai_vector_OA = np.sqrt((OA[0])**2 + (OA[1])**2 + (OA[2])**2)
print("Chiều dài vector OA là: ", chieu_dai_vector_OA)

[ 7 -5  8]
Chiều dài vector OA là:  11.74734012447073


Bài 5: Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB và tính chiều dài của vector này ‖AB‖. Lưu ý: sử dụng Numpy.

In [11]:
import numpy as np

n = int(input("Nhập n: "))
A = np.random.randint(-10, 10, n)
print(A)
B = np.random.randint(-10, 10, n)
print(B)

vector_AB = B-A
print("Vector AB là: ", vector_AB)

chieu_dai_vector_AB = np.sqrt((vector_AB[0])**2 + (vector_AB[1])**2 + (vector_AB[2])**2)
print("Chiều dài vector AB là: ", chieu_dai_vector_AB)

Nhập n: 4
[ 0  2  5 -9]
[-6 -2  2 -9]
Vector AB là:  [-6 -4 -3  0]
Chiều dài vector AB là:  7.810249675906654


Bài 6: Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 vector a & b và tính tích vô hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.inner()

In [12]:
import numpy as np

n = int(input("Nhập n: "))

a = np.random.randint(-10, 10, n)
print("vector a là: ", a)

b = np.random.randint(-10, 10, n)
print("vector b là: ", b)

tich_vo_huong = np.inner(a, b)
print("tích vô hướng của 2 vector a và b là: ", tich_vo_huong)

Nhập n: 4
vector a là:  [9 7 9 5]
vector b là:  [ -2   3 -10  -6]
tích vô hướng của 2 vector a và b là:  -117


Bài 7: Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 vector a & b và tính tích hữu hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.cross()

In [14]:
import numpy as np

n = int(input("Nhập n: "))

a = np.random.randint(-10, 10, n)
print("vector a là: ", a)

b = np.random.randint(-10, 10, n)
print("vector b là: ", b)

tich_huu_huong = np.cross(a, b)
print("tích hữu hướng của 2 vector a và b là: ", tich_huu_huong)

Nhập n: 3
vector a là:  [ -4 -10   9]
vector b là:  [7 4 1]
tích hữu hướng của 2 vector a và b là:  [-46  67  54]


Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được thực hiện thông qua thao tác a.T
Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian $R^n$, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a .

In [16]:
import numpy as np

n = int(input("Nhập n: "))

a = np.random.randint(-10, 10, n)
print("vector a là: ", a, sep = '\n')

print("Chuyển vị của vector a là: ", a.T, sep = '\n')

Nhập n: 5
vector a là: 
[-3  6  5  0  8]
Chuyển vị của vector a là: 
[-3  6  5  0  8]


Bài 9 - Kết hợp cấu trúc list với Numpy:
1. a = [1, 2, 3, 4, 5]
2. b = [[1], [2], [3], [4], [5]]

Hãy:
- Xuất a và b ra màn hình
- Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
- Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [17]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]

aa = np.array(a)
bb = np.array(b)

print(a)
print(b)

print("vector a là: ", aa)
print("vector b là: ", bb, sep = '\n')

print("Chuyển vị của vector a là: ", aa.T)
print("Chuyển vị của vector b là: ", bb.T)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
vector a là:  [1 2 3 4 5]
vector b là: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Chuyển vị của vector a là:  [1 2 3 4 5]
Chuyển vị của vector b là:  [[1 2 3 4 5]]


Bài 10: Trong không gian $R^n$, hãy sinh ngẫu nhiên vector a và b, n là số nguyên dương nhập vào từ bàn phím. 

Hãy:

-Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình

-Thực hiện phép cộng 2 vector: a + b và xuất kết quả ra màn hình.

In [18]:
import numpy as np
import random

n = int(input("nhập n: "))

a = np.random.randint(-10, 10, n)
print(a)
b = np.random.randint(-10, 10, n)
print(b)

m = int(input("nhập m: "))

print("a*m: \n", a*m)
print("a+b là: \n", a+b)

nhập n: 4
[-9  9  1 -8]
[ 0  7  6 -6]
nhập m: 3
a*m: 
 [-27  27   3 -24]
a+b là: 
 [ -9  16   7 -14]
