<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/b%C3%A0i_t%E1%BA%ADp_numpy_s%E1%BB%91_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian R3, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
A = np.array([5,7,14])
print(A)

[ 5  7 14]


Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [ ]:
import numpy as np
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [ ]:
import numpy as np

n = int(input("Nhập n: "))
A = np.random.randint(low=-10, high=10, size=(1,n))
print(A)

Nhập n: 4
[[ 0  7 -8 -9]]


Bài 4: Hãy viết chương trình tính chiều dài của vector OA=[7,-5,8]

In [ ]:
import numpy as np

OA = np.array([7,-5,8])
print(OA)
chieu_dai_vector_OA = np.sqrt((OA[0])**2 + (OA[1])**2 + (OA[2])**2)
print("Chiều dài vector OA là: ", chieu_dai_vector_OA)

[ 7 -5  8]
Chiều dài vector OA là:  11.74734012447073


Bài 5: Trong không gian Rn, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB và tính chiều dài của vector này ‖AB‖. Lưu ý: sử dụng Numpy.

In [ ]:
import numpy as np

n = int(input("Nhập n: "))
A = np.random.randint(low=-10, high=10, size=(1,n))
print(A)
B = np.random.randint(low=-10, high=10, size=(1,n))
print(B)

vector_AB = B-A
print("Vector AB là: ", vector_AB)

chieu_dai_vector_AB = np.sqrt((vector_AB[0][0])**2 + (vector_AB[0][1])**2 + (vector_AB[0][2])**2)
print("Chiều dài vector AB là: ", chieu_dai_vector_AB)

Nhập n: 4
[[ 0  6 -8  8]]
[[ 1  8 -3 -1]]
Vector AB là:  [[ 1  2  5 -9]]
Chiều dài vector AB là:  5.477225575051661


Bài 6: Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b và tính tích vô hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.inner()

In [ ]:
import numpy as np

n = int(input("Nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print("vector a là: ", a)

b = np.random.randint(low=-10, high=10, size=(1,n))
print("vector b là: ", b)

tich_vo_huong = np.inner(a, b)
print("tích vô hướng của 2 vector a và b là: ", tich_vo_huong)

Nhập n: 5
vector a là:  [[ -2   9 -10  -1   5]]
vector b là:  [[ -6   9 -10   0  -3]]
tích vô hướng của 2 vector a và b là:  [[178]]


Bài 7: Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b và tính tích hữu hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.cross()

In [ ]:
import numpy as np

n = int(input("Nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print("vector a là: ", a)

b = np.random.randint(low=-10, high=10, size=(1,n))
print("vector b là: ", b)

tich_huu_huong = np.cross(a, b)
print("tích hữu hướng của 2 vector a và b là: ", tich_huu_huong)

Nhập n: 3
vector a là:  [[ 3 -8 -1]]
vector b là:  [[-8 -6 -5]]
tích hữu hướng của 2 vector a và b là:  [[ 34  23 -82]]


Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được thực hiện thông qua thao tác a.T
Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a .

In [ ]:
import numpy as np

n = int(input("Nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print("vector a là: ", a, sep = '\n')

print("Chuyển vị của vector a là: ", a.T, sep = '\n')

Nhập n: 8
vector a là: 
[[-10   6  -9   9   8  -9   7   4]]
Chuyển vị của vector a là: 
[[-10]
 [  6]
 [ -9]
 [  9]
 [  8]
 [ -9]
 [  7]
 [  4]]


Bài 9 - Kết hợp cấu trúc list với Numpy:
1. a = [1, 2, 3, 4, 5]
2. b = [[1], [2], [3], [4], [5]]

Hãy:
- Xuất a và b ra màn hình
- Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
- Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [ ]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]

aa = np.array(a)
bb = np.array(b)

print(a)
print(b)

print("vector a là: ", aa)
print("vector b là: ", bb, sep = '\n')

print("Chuyển vị của vector a là: ", aa.T)
print("Chuyển vị của vector b là: ", bb.T)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
vector a là:  [1 2 3 4 5]
vector b là: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Chuyển vị của vector a là:  [1 2 3 4 5]
Chuyển vị của vector a là:  [[1 2 3 4 5]]


Bài 10: Trong không gian Rn, hãy sinh ngẫu nhiên vector a và b, n là số nguyên dương nhập vào từ bàn phím. 

Hãy:

-Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình

-Thực hiện phép cộng 2 vector: a + b và xuất kết quả ra màn hình.

In [ ]:
import numpy as np
import random

n = int(input("nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print(a)
b = np.random.randint(low=-10, high=10, size=(1,n))
print(b)

m = int(input("nhập m: "))

print("a*m: \n", a*m)
print("a+b là: \n", a+b)

nhập n: 5
[[-1  8 -9  6  1]]
[[ -9 -10   9   1   4]]
nhập m: 4
a*m: 
 [[ -4  32 -36  24   4]]
a+b là: 
 [[-10  -2   0   7   5]]
