<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/b%C3%A0i_t%E1%BA%ADp_numpy_s%E1%BB%91_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

In [ ]:
# CÚ PHÁP: np.apply_along_axis(func1d, axis, arr, args, kwargs)

# func1d(hàm): hàm này chấp nhận mảng 1 chiều,nó được áp dụng cho các mảng 1 chiều của ma trận theo trục được chỉ định
# axis(số nguyên): trục dọc của ma trận được cắt
# arr(ma trận): ma trận được nhập vào
# args: đối số bổ sung cho func1d
# kwargs: đối số được đặt tên bổ sung cho func1d

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
import numpy as np

A = np.random.randint(low=-20, high=20, size=(15,17))
print("ma trận A15x17: \n", A)

ma trận A15x17: 
 [[-18  19  -8   0   9   3 -13 -15  -6   7  -6  17  -1  -3   5   8   9]
 [ -3  18 -20 -17 -13  -4  19  10  -6  -8 -15 -12   2  -5  -9   2 -15]
 [  5  -6  -1  10 -17  -3  12 -18  15  12  15  -2  11   5   0  15   3]
 [  7 -20 -14   4  -5  19   5  -6  19   9  13  10  14  -3  -6   4 -16]
 [  0  13  11 -17  15 -18  19   2   4   5 -19 -11 -11 -15  13   6  -8]
 [ -1  -2  17  14   0  17 -17 -18   5  -7  15  10 -11  -4 -15  -5   6]
 [ 14  16  17  13   3   4  -6 -19 -10   1   9  -2  17   1   8 -20 -13]
 [  6 -16 -10 -16  17 -18   4   3   9   5  14  -9 -12 -19  13   7   3]
 [-20  16  15 -20   1   4 -14   0   5  -9  -2   8 -20  10 -18   8  13]
 [ -9   6  -6  -5 -18   0  17 -11 -20  -4  -8   3 -15  18  17 -13   8]
 [ -3  -9  13  -9  -6   6  14   5  14 -13   6  17   7 -11 -19  -4  -2]
 [  2  14   7   7  15   8  11  -2 -17  -2  17  10  -8   9 -11  12   7]
 [  1  -1 -13  -5   2   2  15  18  13  -4   7 -12  -9  15   5  -2  12]
 [-15  -1  13   7  16   8 -17  19  10   4  -6 -16   5  17 -

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_lon_nhat(vector_a):
  max = np.max(vector_a)
  return max
# 0,-2 cột
# 1,-1 hàng
z = np.apply_along_axis(tim_gia_tri_lon_nhat, 1, A)
print(z)

[19 19 15 19 19 17 17 17 16 18 17 17 18 19 13]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_nho_nhat(vector_a):
  min = np.min(vector_a)
  return min

q = np.apply_along_axis(tim_gia_tri_nho_nhat, 0, A)
print(q)

[-20 -20 -20 -20 -18 -18 -17 -19 -20 -13 -19 -16 -20 -19 -19 -20 -16]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong(vector_a):
  tong = np.sum(vector_a)
  return tong
# 0,-2 cột
# 1,-1 hàng
w = np.apply_along_axis(tinh_tong, 1, A)
print(w)

[  7 -76  56  34 -11   4  33 -19 -23 -40   6  79  44  33  13]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong_2(vector_a):
  vector_a=0
  for i in range (A):
    if i%2 == 0:
      vector_a == 

    if i%2 != 0:


  tong2 = np.sum(vector_a)