<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/b%C3%A0i_t%E1%BA%ADp_pandas_1_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SERIES:**
- Một Series tương tự như một danh sách hoặc một mảng trong Python. Nó đại diện cho một loạt các giá trị (số hoặc cách khác), chẳng hạn như một cột dữ liệu. Hãy nghĩ về nó như một danh sách Python trên steroid. Nó cung cấp thêm chức năng, phương thức và toán tử, làm cho nó trở thành phiên bản mạnh hơn của danh sách.
- Khai báo thư viện: ***import pandas as pd***

Câu 1: Khởi tạo 1 Series với giá trị rỗng

In [ ]:
import pandas as pd
a = pd.Series([])
print(a)

Series([], dtype: float64)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


Câu 2: Giả sử có 1 vector hàng a có kích thước (1x7) được biểu diễn trong NumPy, hãy tạo 1 series tương ứng với các giá trị được sinh ngẫu nhiên.

In [ ]:
import numpy as np
import pandas as pd

b = pd.Series(np.random.randint(10,size = 7))
print(b.values)

[0 7 8 3 8 8 0]


Câu 3: Giả sử có 1 vector hàng a có kích thước (1x7), hãy nhập các giá trị cho 7 phần tử này từ bàn phím và tạo series tương ứng.

In [ ]:
import numpy as np
import pandas as pd

c1 = int(input("Nhập: "))
c2 = int(input("Nhập: "))
c3 = int(input("Nhập: "))
c4 = int(input("Nhập: "))
c5 = int(input("Nhập: "))
c6 = int(input("Nhập: "))
c7 = int(input("Nhập: "))

cc = [c1,c2,c3,c4,c5,c6,c7]
a = np.array(cc)
print(a)
a2 = pd.Series(a)
print(a2)

Nhập: 3
Nhập: 5
Nhập: 0
Nhập: 2
Nhập: 0
Nhập: 7
Nhập: 8
[3 5 0 2 0 7 8]
0    3
1    5
2    0
3    2
4    0
5    7
6    8
dtype: int64


Câu 4: Giả sử có 1 vector cột có kích thước (7x1) được biểu diễn trong NumPy, hãy tạo Series tương ứng.

In [6]:
import numpy as np
import pandas as pd
a = np.random.randint(low=-10, high=10, size=(7,1))
print(a)
print(pd.Series(a.reshape(7,)))

[[  0]
 [-10]
 [  3]
 [  4]
 [  4]
 [ -6]
 [ -9]]
0     0
1   -10
2     3
3     4
4     4
5    -6
6    -9
dtype: int64


Câu 5: Chuyển đổi dữ liệu, hãy thực hiện các yêu cầu sau:
- Chuyển 1 list thành 1 series
- Chuyển 1 tuple thành 1 series
- Chuyển 1 dictionary thành 1 series

In [ ]:
import numpy as np
import pandas as pd

a = [1,2,3,4,5]
b = (6,7,8,9,10)
c = {'n':1, "u":2, "m":3, "p":4, "y":5}

aa = pd.Series(a)
print(aa)
bb = pd.Series(b)
print(bb)
cc = pd.Series(c)
print(c)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     6
1     7
2     8
3     9
4    10
dtype: int64
{'n': 1, 'u': 2, 'm': 3, 'p': 4, 'y': 5}


Câu 6: Mỗi phần tử của series đều gắn liền với các chỉ số (index) tương ứng, hãy tạo một series
có kích thước (1x20) với giá trị ngẫu nhiên:
- Xuất series ra màn hình
- Xuất các chỉ số của series ra màn hình
- Thay đổi cách đánh chỉ số mặc định của series từ đánh chỉ số bằng số nguyên sang các kiểu
đánh chỉ số bằng label và in kết quả ra màn hình
Gợi ý:
- Hàm loc() dùng cho chỉ số label
- Hàm iloc() dùng cho chỉ số đạng số nguyên
- Hàm ix(): dùng cho cả 2 loại chỉ số trên

In [45]:
import numpy as np
import pandas as pd

shi = np.random.randint(low=-10, high=10, size=(1,20))
print(shi) #xuất series ra màn hình
print(pd.Series(shi[0])) #xuất các chỉ số của series ra màn hình

label = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t"]
#Thay đổi cách đánh chỉ số mặc định của series từ đánh chỉ số bằng số nguyên sang các kiểu đánh chỉ số bằng label 
print(pd.Series(shi[0], index = label)) 
print(shi.loc[["a","c","e"]])


[[ -1   1  -4   7  -6  -9  -9  -2  -5  -8  -7 -10   0   8 -10  -6   8  -6
   -9  -3]]
0     -1
1      1
2     -4
3      7
4     -6
5     -9
6     -9
7     -2
8     -5
9     -8
10    -7
11   -10
12     0
13     8
14   -10
15    -6
16     8
17    -6
18    -9
19    -3
dtype: int64
a    -1
b     1
c    -4
d     7
e    -6
f    -9
g    -9
h    -2
i    -5
j    -8
k    -7
l   -10
m     0
n     8
o   -10
p    -6
q     8
r    -6
s    -9
t    -3
dtype: int64


AttributeError: ignored

Câu 7: Giả sử có series có kích thước (1x10), giá trị ngẫu nhiên, index được đánh từ ‘a’ trở đi,
hãy:
- Trích xuất các phần tử của Series có chỉ số là ‘a’, ‘c’, ‘e’
- Trích xuất các phần tử của Series có chỉ số từ 3 đến 6

In [48]:
import numpy as np
import pandas as pd

do = np.random.randint(low=0,high=10,size=(1,10))
la = ["a","b","c","d","e","f","g","h","i","j"]
S = pd.Series(do[0],index=la)
print(S)

a    2
b    5
c    7
d    9
e    9
f    4
g    5
h    2
i    4
j    8
dtype: int64
