<a href="https://colab.research.google.com/github/NGONGOCHA/HK2-nam1/blob/main/X%C3%A2y_d%E1%BB%B1ng_t%C3%A0i_li%E1%BB%87u_k%E1%BB%B9_thu%E1%BA%ADt_v%E1%BB%81_ki%E1%BB%83m_%C4%91%E1%BB%8Bnh_T_b%E1%BA%B1ng_g%C3%B3i_statsmodels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Các Thư viện

In [1]:
import numpy as np
import pandas as pd
import random 
from scipy import stats
from statsmodels.stats.weightstats import ttest_ind
import math
import statsmodels.stats.weightstats
import matplotlib.pyplot as plt
import seaborn as sns
import warnings


/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


2. Thiết lập định dạng hình ảnh

In [2]:
sns.set(rc={'figure.figsize':(13, 7.5)})
sns.set_context('talk')

3. Tắt các cảnh báo của scipy

In [3]:
warnings.filterwarnings('ignore')

4. Một số lưu ý khi kiểm định giả thuyết trong thống kê suy diễn


(1) Cỡ mẫu nhỏ (n<30) để có ý nghĩa thống kê

(2) Các mẫu quan sát được (sample observations) phải được lựa chọn ngẫu nhiên từ quần thể

(3) Các đại lượng như trung bình mẫu (sample mean), độ lệch chuẩn của mẫu (standard deviation), phương sai mẫu (sample variance) được tính từ tập mẫu quan sát được.

(4) Giả định rằng quần thể được nghiên cứu lấy mẫu xấp xỉ với phân phối chuẩn.

5. Các bước kiểm định:

Bước 1: Thực hiện các phép đo, hay thu thập dữ liệu quan sát

Bước 2: Phát biểu giả thuyết  $H_0$  và giả thuyết thay thế  $H_A$

Bước 3: Xác định mức  $\alpha$  (hay khoảng tin cậy)

Bước 4: Lấy mẫu và tính toán các đại lượng thống kê của mẫu

Bước 5: Thực hiện kiểm định t (t-test)

Bước 6: Kết luận dựa vào kết quả kiểm định

6. Xây dựng một kiểm định t cụ thể với số liệu được sinh ngẫu nhiên theo phân phối chuẩn

Bài toán: : Tiền lương hàng tháng của 20 công nhân cơ khí tại Bình Dương có trung bình mẫu là 12 triệu đồng và độ lệch chuẩn mẫu là 2,5 triệu đồng. Tiền lương trung bình hàng tháng của công nhân cơ khí tại Đà Nẵng là 14 triệu đồng. Với mức ý nghĩa 5%, có thể cho rằng tiền lương trung bình hàng tháng của công nhân cơ khí tại Bình Dương thấp hơn tại Đà Nẵng hay không? 

**Kiểm định 1 đuôi**

Xây dựng giả thuyết:

$$H_0 : \mu = 14$$

Giả thuyết thay thế:

$$H_a : \mu < 14$$

với:
- Hệ số alpha : 0,05  
- Chỉ số t với bậc tự do 19 (20-1) tương ứng với α/2 = 0.025 là 2.093 (bảng phân phối t)

Công thức:  
$$t = \frac{(\overline{\rm X} - \mu_0)}{(s / \sqrt{n})}$$
với:
- $\overline{\rm X}$: trung bình mẫu
- $\mu_{0}$: trung bình của tổng thể cần so sánh
- s: độ lệch chuẩn hiệu chỉnh mẫu
- n: cỡ mẫu

Áp dụng với các giá trị nêu trên:
- $\overline{\rm X}$: 12
- $\mu_{0}$: 14
- s : 2,5
- n: 20
$$t = \frac{(12 - 14)}{(2,5 / \sqrt{20})} \approx -3,577$$

Giá trị $|t|$ = -3,577 < 2,093 nên không có bằng chứng để bác bỏ giả thuyết $H_0$




In [4]:
#Sinh ngẫu nhiên 20 mẫu tuân theo phân phối chuẩn có trung bình mẫu là 12 và độ lệch chuẩn là 2.5
samples = np.random.normal(12, scale=2.5,size = 20)
# print(samples[:10])
samples

array([14.90280386, 10.02323511,  9.60774262,  9.98772943, 13.35872667,
       14.39848268,  9.40305546, 10.99331824, 14.32061989,  9.87115686,
       12.21264712, 13.22703204, 10.98035321, 10.48489466, 17.07040812,
       13.0700839 , 10.61186508, 11.37922526, 10.44104547,  7.69158047])

In [5]:
#Xác định các thông số
null_mean = 20
alpha = 0.05

In [6]:
#Kiem dinh t 
t_test, p_value= stats.ttest_1samp(samples, null_mean)
print("p_value: ",p_value)
if(p_value < alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

p_value:  1.5337965989791384e-12
Có bằng chứng để bác bỏ giả thuyết H0


**Kiểm định 2-đuôi**

Bài toán: : Tiền lương hàng tháng của 20 công nhân cơ khí tại Bình Dương có trung bình mẫu là 12 triệu đồng và độ lệch chuẩn mẫu là 2,5 triệu đồng. Tiền lương trung bình hàng tháng của công nhân cơ khí tại Đà Nẵng là 14 triệu đồng. Với mức ý nghĩa 5%, có thể cho rằng tiền lương trung bình hàng tháng của công nhân cơ khí tại Bình Dương và tại Đà Nẵng như nhau hay không? 

Xây dựng giả thuyết:
\begin{align}
        H_0: μ = 14
    \end{align}

Giả thuyết thay thế:
\begin{align}
        H_a: μ_1 \ne 14
    \end{align}

với:
- Hệ số alpha : 0,05  
- Chỉ số t với bậc tự do 19 (20-1) tương ứng với α/2 = 0.025 là 2.093 (bảng phân phối t)


Công thức:  
$$t = \frac{(\overline{\rm X} - \mu_0)}{(s / \sqrt{n})}$$
với:
- $\overline{\rm X}$: trung bình mẫu
- $\mu_{0}$: trung bình của tổng thể cần so sánh
- s: độ lệch chuẩn hiệu chỉnh mẫu
- n: cỡ mẫu

Áp dụng với các giá trị nêu trên:
- $\overline{\rm X}$: 12
- $\mu_{0}$: 14
- s : 2,5
- n: 20
$$t = \frac{(12 - 14)}{(2,5 / \sqrt{20})} \approx -3,577$$

Giá trị $|t|$ = -3,577 < 2,093 nên không có bằng chứng để bác bỏ giả thuyết $H_0$

In [16]:
#Sinh ngẫu nhiên sample 1 có 20 mẫu với trung bình mẫu là 12 và độ lệch chuẩn là 2.5
samples1 = np.random.normal(12, scale=2.5,size = 20)
# print(samples[:10])
samples1

array([10.88799592, 18.7910172 , 12.60517682, 10.21711532, 13.66885003,
       14.15708361, 10.06189532, 15.48916001, 14.02046725, 13.2374674 ,
       14.8757299 ,  8.4094741 , 10.6840859 , 13.19376185, 12.66067036,
       14.78854395, 12.10168097, 10.81086517, 14.85718222,  9.45400516])

In [12]:
#Sinh ngẫu nhiên sample 2 có 20 mẫu với trung bình mẫu là 12 và độ lệch chuẩn là 2.5
samples2 = np.random.normal(12, scale=2.5,size = 20)
# print(samples[:10])
samples2

array([12.36868669,  9.78270223, 11.42130298, 12.7777311 , 16.95249354,
       14.87922588,  9.5401131 ,  9.50032767, 12.44621221, 11.72791158,
       10.8865929 , 10.06876614, 12.07486159, 12.38736114, 10.44539136,
       12.06918052, 17.41270172,  8.71476709, 11.41310971,  8.52345732])

In [17]:
#Kiểm định giả thuyết 
alpha = 0.05
t_test, p_value,df = ttest_ind(x1 = samples1, x2 = samples2, value = 14-12 , alternative = 'two-sided')
print('t = ', t_test, '; p = ', p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

t =  -1.3191266868928138 ; p =  0.19502075754168163
Chưa có bằng chứng để bác bỏ giả thuyết H0
